# Generated by Django 4.0.4 on 2022-04-15 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_alter_user_managers_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tt_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wpm_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tt_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wpm_diff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tt_diff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
