# Generated by Django 4.0.4 on 2022-04-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
